### ISSUE TITLE
Some hints from the DevExtreme team 

### ISSUE THREAD

**Issue by dxbykov** [MihaMarkic/BlazorDevExtreme#1]
Hi,

It's exciting to see this project ;) I just want to give you some hints you might find helpful to go forward faster. We have created wrappers for [Angular](https://github.com/DevExpress/devextreme-angular), [React](https://github.com/DevExpress/devextreme-react), [Vue](https://github.com/DevExpress/devextreme-vue) and ASP.Net MVC using the same approach. 
 
We have a [3rd-Party Frameworks Integration API](https://js.devexpress.com/Documentation/Guide/Widgets/Common/Advanced/3rd-Party_Frameworks_Integration_API/) that we use in our wrappers' implementation. It's jQuery-free. 
 
Also, we have [Integration Meta Data](https://github.com/DevExpress/devextreme-react/blob/master/tools/integration-data.json) that contains all the public API info. We use this info to [generate component source code](https://github.com/DevExpress/devextreme-react/blob/master/tools/src/component-generator.ts). The generated components extend a [base component](https://github.com/DevExpress/devextreme-react/blob/master/src/core/component.ts) implementation.
 
Feel free to ask any integration-related questions in our [Support Center](https://www.devexpress.com/Support/Center/) or in this thread.

**Comment by MihaMarkic** [comment]
Thanks a lot, I'm currently parsing TypeScript interface but IMD will be easier to deal with.
Eventually a better approach will be react-like. But there are showstoppers in blazor currently.
Anyway, I'll certainly bug you with questions :)
