### ISSUE TITLE
Not working with server-side Blazor

### ISSUE THREAD

**Issue by sven5** [MihaMarkic/BlazorDevExtreme#10]
Hi Miha,

I'd like to use your lib together with a server-side Blazor app.

I get an error
`Unable to cast object of type 'Microsoft.AspNetCore.Blazor.Server.Circuits.RemoteJSRuntime' to type 'Microsoft.JSInterop.IJSInProcessRuntime'`

Is it possible to change the behavior or add a switch to the lib for server-side?

Thanks
Sven

**Comment by sven5** [comment]
Hi Miha,

I uploaded a simple solution to my repo: https://github.com/sven5/Blazor-DevExtreme 
When running the sample you see that the DevExtreme button is not initialized an missing. 
What I've found out so far is that there is an error when using `((IJSInProcessRuntime)JSRuntime.Current).Invoke`. For server-side Blazor it should be something like `JSRuntime.Current.InvokeAsync` because the JsRuntine is not an in-process runtime.

Thank  you
Sven

**Comment by MihaMarkic** [comment]
@sven5 Looking at your repro I see that it isn't working - how did you even find what the error is? Browser nor VS show any message.

**Comment by MihaMarkic** [comment]
I think I know how to solve it. Hopefully over the weekend.

**Comment by MihaMarkic** [comment]
@sven5 Updated NuGet package to 0.6.1. Give it a try.
