### ISSUE TITLE
Example datagrid

### ISSUE THREAD

**Issue by avandijk** [MihaMarkic/BlazorDevExtreme#9]
Hi,

I am looking into the library but I cannot find a way to assign a datasource to a datagrid.
There is no immediate property 'datasource' available.

Can you give me a hint

Thx

**Comment by sven5** [comment]
Here is a very simple and easy example of a Datagrid:

`        <DxDataGrid Columns="@(new[]{ new DevExpress.Ui.DxDataGridColumn { caption="Name of Customer", dataField="name", dataType="string" },
                                      new DevExpress.Ui.DxDataGridColumn { caption="City", dataField="city", dataType="string" } })"
                    FilterRow="@(new { visible = true })" 
                    DataSource="@(new[] { new { name = "John", city = "London"}, new { name = "Steve", city = "Berlin"}})" 
                    ShowRowLines="true" ShowBorders="true"
                    Pager="@(new { visible = true })" />`

**Comment by MihaMarkic** [comment]
Hey @sven5, that's a really nice example. Do you want to create a PR yourself?

**Comment by sven5** [comment]
Yes I could do that, but as you already know yourself I only have limited time. But maybe I can do that in the next days.

**Comment by MihaMarkic** [comment]
@sven5 I can wait and if you can't make it, let me know. Then I'll add it.

**Comment by MihaMarkic** [comment]
Added with #18, thanks for the code
